site_name: dwani.ai
site_url: https://docs.dwani.ai
repo_url: https://github.com/dwani-ai/docs
theme:
  logo: images/dwani-logo.png
  favicon: images/dwani-favicon.ico
  name: material
  features:
    - content.action.edit
    - content.code.copy
    - content.tabs.link
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy
    - content.tabs
    - content.action
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - attr_list
  - md_in_html
site_dir: site
plugins:
  - search
exclude_docs: |
  *.py
  node_modules/
  *.git
  venv
use_directory_urls: false
nav:
  - home: index.md
  - python SDK: python-sdk.md
  - discovery:
      - readme : discovery/index.md
      - desktop : discovery/desktop.md
      - vLLM Server: discovery/vllm_deploy.md
      - API Server: discovery/api_server_setup.md
      - Proxy Server: discovery/proxy_setup_vm.md
      - Discovery Server : discovery/discovery_setup.md
  - multimodal :
      - readme : multimodal/index.md
      - Docs API: multimodal/docs_setup.md
      - Translate Server: multimodal/translate_server.md
      - TTS Server: multimodal/tts-server.md
      - ASR Server: multimodal/asr_server.md
  - workshop:
      - readme : workshop/index.md
  - examples:
      - readme : examples/index.md
  - misc:
    - readme : misc/index.md
    - arm64:
        - readme : arm64/README.md
        - vLLM wheel : arm64/vllm-setup.md
        - vLLM docker build : arm64/vllm_docker_build.md
        - xfomers : arm64/xfomers.md 
        - flashinfer : arm64/flashinfer.md
        - torch: arm64/torch_2_8.md
    - local:
        - readme : local/index.md
        - llama.cpp : local/llama-cpp.md
        - moondream : local/moondream.md
    - cuda :
        - readme : cuda/index.md
        - cuda driver : cuda/cuda_12_9-setup.md
        - cuda docker : cuda/cuda_docker.md
    - mobile :
        - readme : mobile/index.md
        - android : mobile/android-app.md
    - todo:
        - arm64 upgrade : todo/todo_arm_64_arm64-gpu-tools.md