FROM dwani/vllm-arm64:latest


RUN apt-get update && apt-get install -y python3 python3-pip



RUN pip install https://github.com/dwani-ai/vllm-arm64/releases/download/v0.0.3/vllm-0.10.1.dev47+g8ed01e32f.d20250725-cp312-cp312-linux_aarch64.whl
